@Library('damkins') _

gitVars = [:]

def initGitVars() {
    gitVars = parseGitVars()
}

pipeline {
    agent {
        kubernetes {
            label getAgentLabel()
        }
    }

    options {
        disableConcurrentBuilds(abortPrevious: true)
    }

    environment {
        PATH = initTools()
    }

    stages {
        stage('SonarQube Analysis') {
            steps {
                initGitVars()
                analyze()
            }
        }

        stage('Build Test Image') {
            steps {
                initGitVars()
                buildTestImage(
                    buildID: env.BUILD_ID,
                    repoName: gitVars.repoName,
                )
            }
        }

        stage('Build and Push Image') {
            when {
                expression {
                    env.GIT_BRANCH ==~ /main/
                }
                beforeAgent true
            }

            steps {
                initGitVars()
                buildAndPushImage(
                    buildID: env.BUILD_ID,
                    repoName: gitVars.repoName,
                    branchName: gitVars.branchName,
                    commitHash: gitVars.commitHash,
                )
            }
        }

        stage('Deployment Approval') {
            when {
                expression {
                    env.GIT_BRANCH ==~ /main/
                }
                beforeAgent true
            }

            steps {
                initGitVars()
                approveDeployment(
                    repoName: gitVars.repoName
                )
            }
        }

        stage('Deployment Execution') {
            when {
                expression {
                    env.GIT_BRANCH ==~ /main/
                }
                beforeAgent true
            }

            // environment {
            //     ARGOCD_SERVER = getDeploymentURL(target: 'production')
            //     ARGOCD_AUTH_TOKEN = credentials("${getDeploymentToken(target: 'production')}")
            // }

            // steps {
            //     executeDeployment(
            //         branch: branch,
            //         commitHash: commitHash,
            //         repo_name: getRepoName(),
            //         deployment_image: getDeploymentImage(),
            //         target: 'production',
            //     )
            // }

            steps {
                echo 'Success!'
            }
        }
    }

    post {
        cleanup {
            cleanWs()
        }
    }
}
