@Library('damkins') _

authorName = ''
branchName = ''
commitHash = ''

def initGitVars() {
    commitHash = env.GIT_COMMIT
    branch = env.GIT_BRANCH
    authorName = sh(
        returnStdout: true,
        script: "git show -s --pretty=%an || echo 'null'"
    ).trim()
}

pipeline {
    // options {
    //     disableConcurrentBuilds(abortPrevious: true)
    //     timeout(time: 20)
    //     copyArtifactPermission('*')
    //     buildDiscarder(
    //         logRotator(
    //             numToKeepStr: '20',
    //             artifactNumToKeepStr: '10',
    //             artifactDaysToKeepStr: '10'
    //         )
    //     )
    // }

    stages {
        stage('SonarQube Analysis') {
            steps {
                analyze()
            }
        }

        stage('Build Test Image') {
            steps {
                initGitVars()
                buildTestImage(
                    buildID: env.BUILD_ID,
                    repoName: getRepoName(),
                )
            }
        }

        stage('Build and Push Image') {
            when {
                expression {
                    env.branchName ==~ /main/
                }
                beforeAgent true
            }

            steps {
                initGitVars()
                buildAndPushImage(
                    buildID: env.BUILD_ID,
                    repoName: getRepoName(),
                    branchName: branchName,
                    commitHash: commitHash,
                )
            }
        }

        stage('Deployment Approval') {
            when {
                expression {
                    env.branchName ==~ /main/
                }
                beforeAgent true
            }

            steps {
                approveDeployment(
                    repoName: repoName
                )
            }
        }

        stage('Deployment Execution') {
            when {
                expression {
                    env.branchName ==~ /main/
                }
                beforeAgent true
            }

            // environment {
            //     ARGOCD_SERVER = getDeploymentURL(target: 'production')
            //     ARGOCD_AUTH_TOKEN = credentials("${getDeploymentToken(target: 'production')}")
            // }

            // steps {
            //     initGitVars()
            //     executeDeployment(
            //         branch: branch,
            //         commitHash: commitHash,
            //         repo_name: getRepoName(),
            //         deployment_image: getDeploymentImage(),
            //         target: 'production',
            //     )
            // }

            steps {
                echo 'Success!'
            }
        }
    }

    post {
        cleanup {
            cleanWs()
        }
    }
}
