pipeline {
  agent any

  stages {
    stage('SCM') {
      steps {
        checkout scm
      }
    }

    stage('SonarQube Analysis') {
      def scannerHome = tool 'SonarScanner';

      steps {
        withSonarQubeEnv('rafiandria23') {
          sh "${scannerHome}/bin/sonar-scanner"
        }
      }
    }
  }
}
